steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'asia-east1-docker.pkg.dev/tzar-project/kedro-hello/quickstart-image:tag1', '.']
images:
  - 'asia-east1-docker.pkg.dev/tzar-project/kedro-hello/quickstart-image:tag1'